### ISSUE TITLE
pip install pyinstaller

### ISSUE THREAD

**Issue by Rabb2269** [Pure-L0G1C/Loki#10]
keeps telling me to install pip install pyinstaller

Ive done it multiple times it does not change.
Ive done sudo update pyinstaller 
no updates found

tried again and same thing install pyinstaller

python3.7 newest version

**Comment by Pure-L0G1C** [comment]
Bruh, you have to put some effort on your side. When you can’t try anymore then open a new issue

**Comment by Rabb2269** [comment]
What you think I did... I sat there for 20minutes trying to figure this
out...
It's cool your absolutely no help meaning you have absolutely no idea what
your doing on your end.
Who's code you steal this from?
Pretty sure if reversed I'll find code from other sources.

**Comment by Pure-L0G1C** [comment]
Nah, it’s all mine. But after a the code gets past a certain size there are too many variables to pinpoint out what the cause of a certain issue is. 

Also, you should go look around, tell me who you think I copied it from. I write code because it’s challenging and fun. How challenging and fun would it be if I just copied someone?

Being upset doesn’t give you the right to disrespect other people’s code, especially when you didn’t pay for that code. If you can’t get to work, just go find another code.

**Comment by Pure-L0G1C** [comment]
No one asked you to use it, you decided to use it yourself. Why don't you go design your own or go fine someone else's program.

 This mind of been useless, but the knowledge I gain from making this was really useful, and there's nothing anyone can say or do to take that knowledge away from me. 

See, knowledge is power, the more knowledge you gain the more powerful you become. My [first](https://github.com/Pure-L0G1C/FleX) was not so good, it only had a few stars, but my [second one](https://github.com/Pure-L0G1C/Loki) was much better because off the knowledge I've gained from doing the first one. My third would be much better because of the knowledge I've gained from this one.

Honestly I write programs not because I need them, but because I enjoy learning how things work. If you don't like my work, we're more than welcome to leave, I'm sure there are people out there that have more experience than I do at writing such code. Don't waste your time, go find a real botnet, mine is not worth the headache.
